# coding: utf-8

"""
    DispatchTrack API

    # Authentication The authentication for this API is done via Oauth2 Access Token: - **GetTokenAuth**   You can find the client ID and secret in your application's Admin - Oauth2 Settings tab.   These are then passed via Basic Auth in the request to server's /oauth2/token endpoint to get the access token.   - **Auth**   With the Oauth2 Access Token received from /oauth2/token request, API requests for remaining API endpoints can be made.   It has to be sent as an Authorization Bearer header in the request.   If an invalid or expired access token is used, API will send back a 401 status.     # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.orders_api import OrdersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOrdersApi(unittest.TestCase):
    """OrdersApi unit test stubs"""

    def setUp(self):
        self.api = OrdersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_order_post(self):
        """Test case for add_order_post

        Add Orders  # noqa: E501
        """
        pass

    def test_delete_order_delete(self):
        """Test case for delete_order_delete

        Delete Orders  # noqa: E501
        """
        pass

    def test_export_post(self):
        """Test case for export_post

        Export Orders  # noqa: E501
        """
        pass

    def test_oauth2_token_post(self):
        """Test case for oauth2_token_post

        Get Oauth2 Access Token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
