# coding: utf-8

"""
    DispatchTrack API

    # Authentication The authentication for this API is done via Oauth2 Access Token: - **GetTokenAuth**   You can find the client ID and secret in your application's Admin - Oauth2 Settings tab.   These are then passed via Basic Auth in the request to server's /oauth2/token endpoint to get the access token.   - **Auth**   With the Oauth2 Access Token received from /oauth2/token request, API requests for remaining API endpoints can be made.   It has to be sent as an Authorization Bearer header in the request.   If an invalid or expired access token is used, API will send back a 401 status.     # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ImportOrderCustomFields(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'custom_field_one_name': 'str',
        'custom_field_two_name': 'str'
    }

    attribute_map = {
        'custom_field_one_name': 'custom_field_one_name',
        'custom_field_two_name': 'custom_field_two_name'
    }

    def __init__(self, custom_field_one_name=None, custom_field_two_name=None):  # noqa: E501
        """ImportOrderCustomFields - a model defined in Swagger"""  # noqa: E501
        self._custom_field_one_name = None
        self._custom_field_two_name = None
        self.discriminator = None
        if custom_field_one_name is not None:
            self.custom_field_one_name = custom_field_one_name
        if custom_field_two_name is not None:
            self.custom_field_two_name = custom_field_two_name

    @property
    def custom_field_one_name(self):
        """Gets the custom_field_one_name of this ImportOrderCustomFields.  # noqa: E501


        :return: The custom_field_one_name of this ImportOrderCustomFields.  # noqa: E501
        :rtype: str
        """
        return self._custom_field_one_name

    @custom_field_one_name.setter
    def custom_field_one_name(self, custom_field_one_name):
        """Sets the custom_field_one_name of this ImportOrderCustomFields.


        :param custom_field_one_name: The custom_field_one_name of this ImportOrderCustomFields.  # noqa: E501
        :type: str
        """

        self._custom_field_one_name = custom_field_one_name

    @property
    def custom_field_two_name(self):
        """Gets the custom_field_two_name of this ImportOrderCustomFields.  # noqa: E501


        :return: The custom_field_two_name of this ImportOrderCustomFields.  # noqa: E501
        :rtype: str
        """
        return self._custom_field_two_name

    @custom_field_two_name.setter
    def custom_field_two_name(self, custom_field_two_name):
        """Sets the custom_field_two_name of this ImportOrderCustomFields.


        :param custom_field_two_name: The custom_field_two_name of this ImportOrderCustomFields.  # noqa: E501
        :type: str
        """

        self._custom_field_two_name = custom_field_two_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImportOrderCustomFields, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImportOrderCustomFields):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
