# coding: utf-8

"""
    DispatchTrack API

    # Authentication The authentication for this API is done via Oauth2 Access Token: - **GetTokenAuth**   You can find the client ID and secret in your application's Admin - Oauth2 Settings tab.   These are then passed via Basic Auth in the request to server's /oauth2/token endpoint to get the access token.   - **Auth**   With the Oauth2 Access Token received from /oauth2/token request, API requests for remaining API endpoints can be made.   It has to be sent as an Authorization Bearer header in the request.   If an invalid or expired access token is used, API will send back a 401 status.     # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ServiceOrderAdditionalFields(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'additional_field_one': 'str',
        'additional_field_two': 'str'
    }

    attribute_map = {
        'additional_field_one': 'additional_field_one',
        'additional_field_two': 'additional_field_two'
    }

    def __init__(self, additional_field_one=None, additional_field_two=None):  # noqa: E501
        """ServiceOrderAdditionalFields - a model defined in Swagger"""  # noqa: E501
        self._additional_field_one = None
        self._additional_field_two = None
        self.discriminator = None
        if additional_field_one is not None:
            self.additional_field_one = additional_field_one
        if additional_field_two is not None:
            self.additional_field_two = additional_field_two

    @property
    def additional_field_one(self):
        """Gets the additional_field_one of this ServiceOrderAdditionalFields.  # noqa: E501


        :return: The additional_field_one of this ServiceOrderAdditionalFields.  # noqa: E501
        :rtype: str
        """
        return self._additional_field_one

    @additional_field_one.setter
    def additional_field_one(self, additional_field_one):
        """Sets the additional_field_one of this ServiceOrderAdditionalFields.


        :param additional_field_one: The additional_field_one of this ServiceOrderAdditionalFields.  # noqa: E501
        :type: str
        """

        self._additional_field_one = additional_field_one

    @property
    def additional_field_two(self):
        """Gets the additional_field_two of this ServiceOrderAdditionalFields.  # noqa: E501


        :return: The additional_field_two of this ServiceOrderAdditionalFields.  # noqa: E501
        :rtype: str
        """
        return self._additional_field_two

    @additional_field_two.setter
    def additional_field_two(self, additional_field_two):
        """Sets the additional_field_two of this ServiceOrderAdditionalFields.


        :param additional_field_two: The additional_field_two of this ServiceOrderAdditionalFields.  # noqa: E501
        :type: str
        """

        self._additional_field_two = additional_field_two

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ServiceOrderAdditionalFields, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ServiceOrderAdditionalFields):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
